// All original nodes remain in the inventory. Unreviewed != absent in Shanghai.
let comparisonView='differences',auditDomain='',auditQuery='',auditFilter='all';
const auditViews={differences:['Differences in depth','具体差异'],inventory:['Every Marble point','全部知识点去向'],policy:['Policy & learning goals','总方针与培养目标'],books:['Textbook evidence','教材与教研依据']};
const auditKinds={local:['Local content differs','地域内容不同'],candidate:['Candidate · verification needed','差异候选 · 待复核'],shared:['Shared goal · depth to check','目标有交集 · 深度待核'],depth:['Demand / depth differs','要求层次不同'],scope:['Scope / granularity differs','范围或粒度不同']};
const auditRecords=id=>[...shData.audit.rows,...shData.rows].filter(r=>r.topics.includes(id));
const auditNodes=()=>data.topics.filter(n=>n.subject===comparisonSubject);
function auditVisible(){return auditNodes().filter(n=>{
 const records=auditRecords(n.id);
 return (!auditDomain||n.domain===auditDomain)&&(!auditQuery||`${n.id} ${n.name} ${n.description} ${data.zh[n.id].name} ${data.zh[n.id].summary} ${records.map(r=>shText(r.title)).join(' ')}`.toLowerCase().includes(auditQuery.toLowerCase()))&&
 (auditFilter==='all'||auditFilter==='associated'&&records.length||auditFilter==='pending'&&!records.length||auditFilter==='within'&&n.ageRangeStart<=12||auditFilter==='later'&&n.ageRangeStart>12||records.some(r=>r.kind===auditFilter));
 });}
function auditNav(){return `<div class="a-nav" role="group" aria-label="${t('Comparison views','对比视图')}">${Object.entries(auditViews).map(([key,label])=>`<button data-a-view="${key}" aria-pressed="${comparisonView===key}">${t(...label)}</button>`).join('')}</div>`;}
function auditSources(r){return `<details class="c-row-sources"><summary>${t('Evidence & source','依据与来源')}</summary>${r.locator?`<p>${esc(r.locator)}</p>`:''}${r.sources.map(id=>`<div class="c-source">${shSource(id)}</div>`).join('')}</details>`;}
function auditSkills(ids){return ids.length?`<ul class="a-skills">${ids.map(id=>{const n=all.get(id);return `<li><a href="${topicUrl(n)}" target="_blank" rel="noopener">${esc(topicLabel(n))} ↗</a><small>${n.ageRangeStart}–${n.ageRangeEnd} ${t('reference ages','参考岁数')}</small></li>`;}).join('')}</ul>`:`<p>${t('Outside this subject inventory. No direct match is asserted.','超出此学科库存范围，不作直接对应。')}</p>`;}
function auditTable(headers,body,cls=''){return `<div class="c-table-scroll" role="region" aria-label="${t('Comparison table, scroll horizontally','对照表，可左右滑动')}" tabindex="0"><table class="c-table a-table ${cls}"><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;}
function auditDifferences(){
 const rs=shData.audit.rows.filter(r=>r.subject===comparisonSubject);
 return `<p class="a-intro">${t('Read both directions: local requirements can expose gaps in Marble; Marble can add contexts or deeper demands. Related nodes are not equivalent requirements.','双向看：本地要求可以揭示 Marble 的缺项；Marble 也可能增加情境或提高要求。列出相关节点不等于判定要求相同。')}</p>${auditTable([t('Comparison & type','对比项与性质'),t('China / Shanghai evidence','中国／上海依据'),t('Related Marble points','Marble 相关节点'),t('What changes — and how to tell','具体差别 · 怎样辨别')],rs.map(r=>`<tr class="a-row" id="audit-${r.id}"><th scope="row"><strong>${esc(shText(r.title))}</strong><span class="c-badge ${r.kind==='candidate'?'lead':''}">${t(...auditKinds[r.kind])}</span></th><td><p>${esc(shText(r.fact))}</p>${auditSources(r)}</td><td>${auditSkills(r.topics)}</td><td class="a-analysis"><p>${esc(shText(r.analysis))}</p><div class="a-probe"><strong>${t('A useful observation','可用来区分的观察')}</strong><p>${esc(shText(r.probe))}</p></div></td></tr>`).join(''))}<p class="a-note">${t('These are selected, analysed differences—not a complete list of Shanghai requirements. A whole-inventory title/description scan supports the narrowly stated localisation findings; no absent label is treated as absence of the general capability.','这里是已有分析的差异选项，尚非上海全部要求清单。地域缺项判断限于当前库存中明确写出的内容；未找到专门名称，不等于没有相应通用能力。')}</p>`;
}
function auditInventory(){
 const nodes=auditNodes(),found=auditVisible();
 const domains=[...new Set(nodes.map(n=>n.domain))];
 return `<p class="a-intro">${t('Every original point is retained, including unreviewed points and age-13 extensions. Associations below are editorial evidence links, not confirmed textbook coverage.','每个原始点都保留，包含未核对项与13岁起的扩展项。下方关联是编辑建立的证据连接，不是已确认的教材覆盖率。')}</p><div class="a-domains" role="group" aria-label="${t('Domains','领域')}"><button data-a-domain="" aria-pressed="${!auditDomain}">${t('All domains','全部领域')} · ${nodes.length}</button>${domains.map(d=>`<button data-a-domain="${esc(d)}" aria-pressed="${d===auditDomain}">${esc(domainLabel(d))} · ${nodes.filter(n=>n.domain===d).length}</button>`).join('')}</div><div class="a-search"><label for="auditSearch">${t('Find a point or requirement','搜索知识点或要求')}</label><input id="auditSearch" type="search" value="${esc(auditQuery)}" placeholder="${t('Search names, descriptions or original IDs','搜索名称、说明或原始 ID')}"></div><div class="a-filters" role="group" aria-label="${t('Evidence and age filters','依据与年龄筛选')}">${Object.entries({all:['All','全部'],associated:['Has an association','有关联依据'],pending:['Not yet associated','尚未建立关联'],within:['Reference start ≤12','参考起始年龄≤12'],later:['Reference start 13+','参考起始年龄13+'],local:['Local content','地域差异'],depth:['Demand / depth','要求层次']}).map(([key,label])=>`<button data-a-filter="${key}" aria-pressed="${key===auditFilter}">${t(...label)}</button>`).join('')}</div><div id="auditResults">${auditResults(found)}</div>`;
}
function auditResults(found){return `<p class="a-result-count" role="status">${t(`${found.length} / ${auditNodes().length} original points shown`, `显示 ${found.length} / ${auditNodes().length} 个原始知识点`)} · ${t('Age labels come from Marble, not Shanghai grades.','年龄来自 Marble，不是上海年级。')}</p>${found.length?auditTable([t('Original point','原始知识点'),t('What Marble requires','Marble 具体要求'),t('Evidence associations','对应依据与分析'),t('What remains unresolved','尚未解决的问题')],found.map(n=>{const rs=auditRecords(n.id);return `<tr class="a-row" data-a-topic="${n.id}"><th scope="row"><a href="${topicUrl(n)}" target="_blank" rel="noopener">${esc(topicLabel(n))} ↗</a><small>${esc(domainLabel(n.domain))} · ${n.ageRangeStart}–${n.ageRangeEnd} ${t('reference ages','参考岁数')}</small><details><summary>${t('Original ID','原始 ID')}</summary><code>${n.id}</code></details></th><td><p>${esc(lang==='zh'?data.zh[n.id].summary:n.description)}</p></td><td>${rs.length?rs.map(r=>`<button class="a-evidence-link" data-a-record="${r.id}" data-a-destination="${r.kind?'differences':'books'}">${esc(shText(r.title))} →</button><small>${r.kind?t(...auditKinds[r.kind]):t(...statusLabels[r.status])}</small>`).join(''):`<span class="c-badge lead">${t('Not yet associated','尚未建立关联')}</span><p>${t('No evidence association has been established for this point.','尚未为本节点建立证据关联。')}</p>`}</td><td><p>${n.ageRangeStart>12?t('Outside the reference-start ≤12 window. Retained to reconcile the complete count; not a Shanghai omission.','超出参考起始年龄≤12的范围。保留以解释总数，不计作上海缺项。'):rs.length?t('Book volume, required depth and independence still need original Shanghai textbook verification. A related goal does not prove complete coverage.','具体册次、要求深度及独立完成程度仍需上海原书核对。相关目标不能证明完整覆盖。'):t('Do not classify this as a Marble-only skill. Neither presence nor absence in Shanghai has been established.','不能归为“Marble 独有”。尚未证实上海是否覆盖。')}</p></td></tr>`;}).join(''),'a-inventory'):`<div class="c-empty">${t('No points match these filters. Try another domain or clear the search.','没有符合当前条件的点。可更换领域或清空搜索。')}</div>`}`;}
function auditPolicies(){return `<p class="a-intro">${t('National direction → Shanghai implementation → textbook tasks → observed learning. These are different levels of evidence; none automatically proves the next.','国家方针 → 上海实施 → 教材任务 → 实际学习表现。四层依据分别呈现，前一层不能自动证明后一层已经落实。')}</p>${auditTable([t('Policy dimension','方针维度'),t('What the policy says','已查到的政策内容'),t('Comparison & related skills','如何比较 · 相关能力'),t('What to observe','落实到什么表现')],shData.audit.policies.map(r=>`<tr class="a-row"><th scope="row"><strong>${esc(shText(r.title))}</strong></th><td><p>${esc(shText(r.fact))}</p>${auditSources(r)}</td><td class="a-analysis"><p>${esc(shText(r.analysis))}</p><details class="a-neighbours"><summary>${t('Related subject skills, not a policy equivalence','查看相关学科能力，不作政策等同')}</summary>${auditSkills(r.topics[comparisonSubject])}</details></td><td><p>${esc(shText(r.probe))}</p></td></tr>`).join(''))}`;}
function bindAuditLinks(root){root.querySelectorAll('[data-a-record]').forEach(b=>b.addEventListener('click',()=>{comparisonView=b.dataset.aDestination;comparisonStage='all';renderComparison();const target=$('#comparisonPanel').querySelector(comparisonView==='books'?`[data-evidence="${b.dataset.aRecord}"]`:`#audit-${b.dataset.aRecord}`);if(target){target.setAttribute('tabindex','-1');target.focus();target.scrollIntoView({block:'center'});}}));}
function renderComparison(){
 renderTextbookComparison();
 if(!comparisonSubject)return;
 const panel=$('#comparisonPanel'),nodes=auditNodes(),associated=nodes.filter(n=>auditRecords(n.id).length).length,later=nodes.filter(n=>n.ageRangeStart>12).length;
 if(auditDomain&&!nodes.some(n=>n.domain===auditDomain))auditDomain='';
 const statistics=`<div class="a-stats"><div><strong>${nodes.length}</strong><span>${t('original points retained','原始点全部保留')}</span></div><div><strong>${associated}</strong><span>${t('with selected evidence links','已有选定依据关联')}</span></div><div><strong>${nodes.length-associated}</strong><span>${t('not yet associated','尚未建立关联')}</span></div><div><strong>${later}</strong><span>${t('start at 13+ · included above','13岁起 · 含在总数中')}</span></div></div>`;
 const common=`<div class="c-top"><h2>${comparisonSubject==='Mathematics'?t('Shanghai × Marble · Mathematics','上海 × Marble · 数学'):t('Shanghai × Marble · English','上海 × Marble · 英语')}</h2><span class="c-status">${t('Bilateral audit · incomplete textbook evidence','双向对照 · 教材证据未齐')}</span></div><p class="c-subtitle">${t('Ages 0–12 · Shanghai new-textbook pathway, including the 2024 entry cohort.','0–12岁 · 上海新教材路径，包含2024级入学孩子。')}</p>${statistics}<p class="a-note">${t('Evidence links are not a coverage score. Differences can concern context, depth, sequence or goals; unavailable evidence stays unknown.','关联数不是覆盖率。差异可能来自情境、深度、进度或目标；证据不足的部分保留为未知。')}</p>${auditNav()}`;
 if(comparisonView==='books')panel.innerHTML=common+panel.innerHTML.slice(panel.innerHTML.indexOf('<div class="c-stages"'));
 else panel.innerHTML=common+(comparisonView==='inventory'?auditInventory():comparisonView==='policy'?auditPolicies():auditDifferences())+`<details class="c-sources"><summary>${t('Method, scope and sources','方法、范围与来源')}</summary><p>${t('No complete textbook crosswalk or exact overlap percentage is claimed. Shanghai has five primary years; Grade 6 is secondary. All 789 imported subject IDs are retained. A single node may have several associations; it is counted once. Policy neighbours do not increase the association count.','尚未完成全套教材逐项对照，也不提供虚假的重合百分比。上海小学五年，六年级进入初中。两科789个原始 ID 全部保留；一个点可有多个关联，但只计数一次。政策相关节点不计入内容关联数。')}</p><p>${t('Maths items using the April 2022 PDF remain provisional until checked against the May 9 corrected standard. National English levels are not assigned mechanically to Shanghai grades. A missing named item is not proof of missing general competence or absence from the full Marble taxonomy.','引用2022年4月数学文本的条目，仍需与5月9日修正版复核。国家英语级别不机械对应上海年级。没有专门条目，不证明通用能力缺失，也不证明整个 Marble 分类体系没有该内容。')}</p>${Object.keys(shData.sources).map(id=>`<div class="c-source">${shSource(id)}</div>`).join('')}</details><p class="c-footer">${t('Sources checked','来源检查')} ${shData.checked} · ${t('Editorial comparison by Second Path. Official sources are linked per finding.','第二路径编辑对照；各项结论均附来源。')}</p>`;
 panel.querySelectorAll('[data-a-view]').forEach(b=>b.addEventListener('click',()=>{comparisonView=b.dataset.aView;renderComparison();panel.querySelector(`[data-a-view="${comparisonView}"]`)?.focus();}));
 panel.querySelectorAll('[data-a-domain]').forEach(b=>b.addEventListener('click',()=>{auditDomain=b.dataset.aDomain;renderComparison();panel.querySelector(`[data-a-domain="${auditDomain}"]`)?.focus();}));
 panel.querySelectorAll('[data-a-filter]').forEach(b=>b.addEventListener('click',()=>{auditFilter=b.dataset.aFilter;renderComparison();panel.querySelector(`[data-a-filter="${auditFilter}"]`)?.focus();}));
 // innerHTML replacement above recreates the old stage buttons.
 if(comparisonView==='books')panel.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>{comparisonStage=b.dataset.stage;renderComparison();panel.querySelector(`[data-stage="${comparisonStage}"]`)?.focus();}));
 if(comparisonView==='inventory')panel.querySelector('#auditSearch')?.addEventListener('input',e=>{auditQuery=e.target.value;const results=panel.querySelector('#auditResults');results.innerHTML=auditResults(auditVisible());bindAuditLinks(results);});
 bindAuditLinks(panel);
}
renderComparison();
