"""Curated evidence records; deliberately no inferred textbook chapter sequence."""
import json
from pathlib import Path

ROOT = Path(__file__).parent
topics = json.loads((ROOT / 'source.json').read_text())['topics']
def bi(en, zh): return {'en': en, 'zh': zh}
sources = {
 'catalog': {'title': bi('Shanghai autumn 2026 textbook catalogue', '上海市教委：2026年秋季教学用书目录'), 'url': 'https://edu.sh.gov.cn/xxgk2_zdgz_jcjy_04/20260810/339e915d906842caaf98736d562df96a.html', 'kind': bi('Official selection reference; not a chapter list', '官方选书依据；不是课本知识点目录')},
 'digital': {'title': bi('Shanghai digital textbook access', '上海市教委：数字教材平台说明'), 'url': 'https://edu.sh.gov.cn/xxgk2_zhzw_jyta_02/20231024/4fc69936201a44c88bd29352687a5d53.html', 'kind': bi('Official access route', '官方教材获取入口')},
 'transition': {'title': bi('Shanghai kindergarten–primary transition guidance', '上海市教委：幼小科学衔接实施意见'), 'url': 'https://edu.sh.gov.cn/shgy_ywjy_gz_1/20230106/b4d28b1934524e2c9b8d74d460e2ffc7.html', 'kind': bi('Shanghai policy', '上海实施依据')},
 'early': {'title': bi('Early learning guidelines: quantity', '《3–6岁儿童学习与发展指南》：数与量'), 'url': 'https://www.edu.cn/xue_qian_779/20121016/t20121016_856526_28.shtml', 'kind': bi('Ministry text reproduced by CERNET', '教育部正式稿，中国教育网转载')},
 'shapes': {'title': bi('Early learning guidelines: shapes and space', '《3–6岁儿童学习与发展指南》：形状与空间'), 'url': 'https://www.edu.cn/xue_qian_779/20121016/t20121016_856526_29.shtml', 'kind': bi('Ministry text reproduced by CERNET', '教育部正式稿，中国教育网转载')},
 'm1': {'title': bi('Grade 1, volume 1, Shanghai 2024 edition: index', '沪教版五四制数学一年级上册（2024版）目录线索'), 'url': 'https://www.haoduoyun.cc/book/hjb/shuxue/eu1s.shtml', 'kind': bi('Third-party index; original book still to verify', '第三方目录；待与原书复核')},
 'm3': {'title': bi('Grade 3, volume 1: new-book lesson-plan index', '沪教版新教材三年级上册教学设计目录线索'), 'url': 'https://max.book118.com/html/2026/0810/7035106115011141.shtm', 'kind': bi('Third-party lesson plan; not the textbook', '第三方教案；不是课本原文')},
 'e1': {'title': bi('Xuhui: Grade 1 new-book My family teaching', '徐汇区东二小学：一年级新教材 My family 教研'), 'url': 'https://d2xx.xhedu.sh.cn/cms/app/info/doc/index.php/32397', 'kind': bi('School report, March 2025; one unit only', '学校教研记录，2025年3月；仅证明该单元')},
 'e1b': {'title': bi('Qingpu: new-book My Family task design', '青浦区教育学院：新教材 My Family 任务设计'), 'url': 'https://jxxy.qpedu.cn/xxdt/xxdt/505143.htm', 'kind': bi('District teaching report; one unit only', '区级教研记录；仅证明该单元')},
 'project': {'title': bi('Shanghai project learning guidance', '上海市教委：项目化学习指导意见'), 'url': 'https://edu.sh.gov.cn/xxgk2_zdgz_jcjy_01/20230901/d22c1043024d4d0e9d32b85fd3392186.html', 'kind': bi('Shanghai policy; not a textbook chapter', '上海政策；不是教材章节')},
 'm67': {'title': bi('Pudong: new Grade 6–7 maths teaching', '浦东教发院：六、七年级数学新教材培训'), 'url': 'https://jfy.pudong-edu.sh.cn/Web/PDJFY/4560004-4560000016455.htm?Page=963', 'kind': bi('District teaching report, September 2024', '区级教研记录，2024年9月')},
 'enstandard': {'title': bi('National English standard 2022 (background)', '国家英语课标2022（背景资料）'), 'url': 'https://www.esph.com.cn/docs/2025-10/705da262a6e74b088ac658bfe2d757ba.pdf#page=20', 'kind': bi('Background only; not substituted for Shanghai books', '只作背景；不代替上海教材')},
}
rows=[]
def add(id,subject,stage,status,en,zh,sen,szh,indices,den,dzh,refs):
 rows.append(dict(id=id,subject=subject,stage=stage,status=status,title=bi(en,zh),shanghai=bi(sen,szh),topics=[topics[i]['id'] for i in indices],difference=bi(den,dzh),sources=refs))

add('m-play','Mathematics','early','guidance','Quantities in play','游戏中的数量','Compare amounts and count objects in everyday play.','在生活与游戏中比较多少、点数实物。',[396,397,398],'The concepts overlap. Marble splits them into skills; the early-years guide uses play and developmental expectations, not school lessons.','概念有交集。Marble 拆成技能节点，学前指南以游戏与发展表现组织，不是小学课程。',['early','transition'])
add('m-parts','Mathematics','early','guidance','Putting together and taking away','合起来与拿走','Explore adding and removing with objects at the older preschool stage.','大班阶段通过实物操作体验合并、拿走与数量变化。',[320,322,324],'Concrete experience is the connection; this does not prescribe written arithmetic drills or an age deadline.','对应的是实物经验，不等于提前练笔算，也不把参考年龄当达标期限。',['early','transition'])
add('m-shapes','Mathematics','early','guidance','Shapes and space','形状与空间','Explore shapes, position and spatial relationships.','感知形状、位置和空间关系。',[495,496,564],'Marble names individual shape skills. The preschool reference centres on exploration with real objects.','Marble 列出具体图形技能；学前依据强调在实物探索中感知。',['shapes','transition'])
add('m-g1-shape','Mathematics','lower','lead','Recognising shapes','认识图形','The 2024 Grade 1 first-volume index lists solid and plane shapes.','2024版一年级上册目录列出立体图形与平面图形。',[495,496],'Shared concepts; a chapter title cannot establish every shape taught or the required depth. Original-book verification is pending.','概念对应；仅凭目录不能确定具体图形范围和要求深度，仍待原书复核。',['m1'])
add('m-g1-number','Mathematics','lower','lead','Numbers to twenty','20以内的数','The index includes numbers to 10 and then to 20.','目录包含10以内的数、20以内的数。',[739,740,742],'Marble separates writing numerals, teen-number structure and tens. These are candidate links, not an official equivalence.','Marble 分列数字书写、十几的组成与十进位概念。这是候选关联，不是官方等同。',['m1'])
add('m-g1-parts','Mathematics','lower','lead','Parts and wholes','分与合','Parts-and-wholes activities appear in the numbers-to-10 unit.','10以内的数单元中安排分与合。',[321,322],'Several Marble nodes describe related number decompositions. The source title “Number bonds to 9” has a description about making ten; the Chinese guide follows that description.','多个 Marble 节点对应数的分解。其中一个英文标题写“到9”，正文实际描述凑十；中文导读依据正文。',['m1'])
add('m-g1-arithmetic','Mathematics','lower','lead','Early addition and subtraction','初步加减法','The index progresses from arithmetic within 10 to addition within 20.','目录由10以内加减法推进到20以内加法。',[323,329,335],'Marble distinguishes representations, symbols and strategies. A node covering subtraction within 20 is broader than this first-volume entry.','Marble 将表征、符号和策略分开；包含20以内减法的节点，范围比此上册目录条目更宽。',['m1'])
add('m-g3-problem','Mathematics','middle','lead','Two-step calculations and problems','两步计算与应用题','A third-party new-book plan lists two-step arithmetic and word problems.','第三方新教材教案目录列出两步四则运算与应用题。',[362,576],'The selected addition/subtraction node covers only part of four-operation problems. Do not infer full coverage from a matching label.','所选加减两步题节点只覆盖四则问题的一部分，名称相近不等于完全覆盖。',['m3'])
add('m-g3-multiply','Mathematics','middle','lead','Multiplying by one digit','用一位数乘','The plan lists one-digit multiplication of two- and three-digit numbers, with estimation.','教案目录列出一位数乘两、三位数及估算。',[706,351],'The written-multiplication node describes the same number sizes. This is a promising match pending textbook verification.','笔算乘法节点的数位范围相符；这是待课本核实的候选对应。',['m3'])
add('m-g3-geometry','Mathematics','middle','lead','Angles and polygons','角、三角形与四边形','The plan introduces angles, triangles and quadrilaterals.','教案目录包含角、三角形和四边形的初步认识。',[495,516],'Marble has a broad shape-recognition node and a separate angle-concept node; later geometry should not be assumed part of this unit.','Marble 有一般图形识别与独立的角概念节点；不能把后续几何要求一并算进本单元。',['m3'])
add('m-g3-divide','Mathematics','middle','lead','Dividing by one digit','用一位数除','The visible plan includes one-digit divisors and two-digit dividends.','可见教案目录包含一位数除两位数。',[707],'This Marble node reaches four-digit dividends and remainders, so its scope is wider. The full Shanghai unit remains unverified.','这个 Marble 节点还涉及四位数与余数，范围更宽；上海完整单元尚未核实。',['m3'])
add('m-reason','Mathematics','bridge','teaching','Explaining and questioning methods','解释方法与提出问题','Pudong new-book training stresses asking questions, reasoning and real-world problem solving.','浦东新教材教研强调提问、思考过程和真实问题解决。',[574,590,588],'Both value reasoning. Marble makes it individually browsable; the local source is teaching guidance, not a claim that a particular class always practises it.','两者都重视推理。Marble 把它拆成可浏览技能；本地来源是教学导向，不能据此判断每个课堂的落实情况。',['m67','project'])
add('e-family','English','lower','teaching','Talking about family','介绍家人','Shanghai Grade 1 first-volume Unit 6 My family is documented in local new-book teaching reports.','本地新教材教研明确记录一年级上册第6单元 My family。',[183,230],'The Shanghai unit organises language around a theme; Marble groups describing and vocabulary use as reusable skills. Its “with detail” demand may be deeper than the entry task.','上海单元按家庭主题组织；Marble 将描述、使用词汇列为通用能力。节点中的详细表达要求可能高于入门任务。',['e1','e1b'])
add('e-interact','English','lower','teaching','Listening, speaking and performing','听、说与表演','The same teaching report describes listening, speaking, reading and performing activities.','同一教研记录描述听、说、读、演活动。',[187,182],'There is overlap in interaction. A local unit does not by itself verify every discussion rule or independent question-asking requirement in Marble.','互动能力有交集，但一个单元不能证明 Marble 的讨论规则、自主提问要求均已覆盖。',['e1'])
add('e-project','English','all','guidance','Learning through a project','在项目中学习','Shanghai guidance includes subject and cross-subject projects.','上海指导意见包含学科项目与跨学科项目。',[250,267],'Marble lists research-related writing skills. This is a method-level connection; the policy does not establish English proficiency or a textbook-specific writing requirement.','Marble 列有研究相关写作技能。这是方法层面的关联，不代表政策规定了英语水平或某册写作要求。',['project'])

data={'checked':'2026-09-14','cohort':2024,'sources':sources,'rows':rows,
 'scope':bi('Ages 0–12 · Shanghai new-textbook pathway · evidence-building draft','0–12岁 · 上海新教材路径 · 资料核对中'),
 'limits':bi('This is not a complete textbook crosswalk yet. Official catalogues confirm book selection, not chapter content. Grey stages are unverified; third-party leads are labelled. National standards are background only.','尚未完成全套教材逐项对照。官方用书目录只能确认选书依据，不能证明章节内容；灰色学段待核对，第三方线索单独标注。国家课标仅作背景。')}
(ROOT/'shanghai.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print('Wrote',len(rows),'evidence records')
